spring.application.name=codetickets

spring.datasource.url=jdbc:postgresql://localhost/codetickets_db
spring.datasource.username=postgres
spring.datasource.password=phlp

spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always

spring.jpa.hibernate.ddl-auto=update